# Configuration file for InventoryPages
# Created by KevinNovak

# ============================================
# Commands
# ============================================
commands:
  # Clears the current page and hotbar
  #   Add "all" after a clear command to clear all pages and hotbar
  clear:
    # Will override any existing commands with same name
    aliases:
      - 'clear'
      - 'clearinventory'
      - 'clearinvent'
      - 'ci'
      - 'clean'

# ============================================
# Saving
# ============================================
saving:
  # Recommended to keep enabled
  #   If disabled, inventories are only saved when players leave the server
  enabled: true
  # How often should inventories be saved to files, in seconds
  interval: 900

# ============================================
# Logging
# ============================================
logging:
  saves:
    # Show in the console when inventories are saved
    enabled: true
    # Message to be shown in the console
    message: 'All inventories have been saved.'

# ============================================
# Language
# ============================================
# Color codes are supported
#   See http://minecraft.gamepedia.com/Formatting_codes for color codes
#   Use the ampersand symbol "&" before the color code number
#     Ex. "&6" would be gold.
language:
  noPermission: '&4You do not have access to that command.'
  clear: '&6Cleared inventory items from hotbar and current page.'
  clearAll: '&6Cleared inventory items from hotbar and all pages.'
  itemsMerged: '&7Items have been moved to your inventory pages.'
  itemsDropped: '&cYour inventory is full, some items have been dropped.'
