#
#  ___                                  _                            ____
# |_ _|  _ __   __   __   ___   _ __   | |_    ___    _ __   _   _  |  _ \    __ _    __ _    ___   ___
#  | |  | '_ \  \ \ / /  / _ \ | '_ \  | __|  / _ \  | '__| | | | | | |_) |  / _` |  / _` |  / _ \ / __|
#  | |  | | | |  \ V /  |  __/ | | | | | |_  | (_) | | |    | |_| | |  __/  | (_| | | (_| | |  __/ \__ \
# |___| |_| |_|   \_/    \___| |_| |_|  \__|  \___/  |_|     \__, | |_|      \__,_|  \__, |  \___| |___/
#                                                            |___/                   |___/
#  ____                              _              _
# |  _ \    ___    ___    ___     __| |   ___    __| |
# | |_) |  / _ \  / __|  / _ \   / _` |  / _ \  / _` |
# |  _ <  |  __/ | (__  | (_) | | (_| | |  __/ | (_| |
# |_| \_\  \___|  \___|  \___/   \__,_|  \___|  \__,_|
#
#  Author: KevinNovak, Cortez_Romeo
#  Download plugin này miễn phí tại: https://minecraftvn.net
#
# Góp ý báo lỗi tại
# --- discord: Cortez_Romeo
# --- facebook: https://www.facebook.com/thuong.trinh.nguyen.321/

# Tự động lưu
saving:
  enabled: true
  # Bao lâu thì lưu một lần, tính theo giây
  interval: 900