#
#  ___                                  _                            ____
# |_ _|  _ __   __   __   ___   _ __   | |_    ___    _ __   _   _  |  _ \    __ _    __ _    ___   ___
#  | |  | '_ \  \ \ / /  / _ \ | '_ \  | __|  / _ \  | '__| | | | | | |_) |  / _` |  / _` |  / _ \ / __|
#  | |  | | | |  \ V /  |  __/ | | | | | |_  | (_) | | |    | |_| | |  __/  | (_| | | (_| | |  __/ \__ \
# |___| |_| |_|   \_/    \___| |_| |_|  \__|  \___/  |_|     \__, | |_|      \__,_|  \__, |  \___| |___/
#                                                            |___/                   |___/
#  ____                              _              _
# |  _ \    ___    ___    ___     __| |   ___    __| |
# | |_) |  / _ \  / __|  / _ \   / _` |  / _ \  / _` |
# |  _ <  |  __/ | (__  | (_) | | (_| | |  __/ | (_| |
# |_| \_\  \___|  \___|  \___/   \__,_|  \___|  \__,_|
#
#  Author: KevinNovak, Cortez_Romeo
#  Download plugin này miễn phí tại: https://minecraftvn.net
#
# Góp ý báo lỗi tại
# --- discord: Cortez_Romeo
# --- facebook: https://www.facebook.com/thuong.trinh.nguyen.321/

# Dùng chủ yếu cho việc sửa lỗi, khi bật sẽ hiện log những hành động đã được thực thi trên console
debug:
  enabled: false
  prefix: '&e[InventoryPagesRecoded Debug] '

# Dùng để thống kê số lượng người chơi sử dụng plugin này
# Không ảnh hưởng đến hiệu năng máy chủ
bStats:
  enabled: true

# Tự động lưu
auto-saving:
  enabled: true
  # Bao lâu thì lưu một lần, tính theo giây
  interval: 900

# Kiểu dữ liệu để hệ thống dựa vào đó mà quản lý
# Hiện tại mình chỉ làm 2 kiểu dữ liệu, bao gồm:
#   * MYSQL (BETA)
#       mysql là kiểu dữ liệu cho phép bạn quản lý dữ liệu trên nhiều nền
#       tảng khác nhau, với lựa chọn này, người chơi có thể kết nối tới
#       túi đồ ở nhiều máy chủ khác nhau, dữ liệu này vẫn đang trong giai đoạn
#       thử nghiệm nên có thể gây lỗi, vui lòng cân nhắc trước khi sử dụng!
#   * YAML (Khuyến khíchh nên xài)
#       lưu và quản lý trực tiếp dữ liệu vào file, khuyến khích nên xài nếu
#       bạn dùng plugin này để quản lý túi đồ người chơi cho một máy chủ
#       duy nhất
database:
  # MYSQL, YAML
  type: YAML
  # Nếu sử dụng MySQL, vui lòng điền thông tin chính xác
  # Nếu dữ liệu không thể kết nối, sẽ chuyển sang sử dụng YAML
  mysql:
    database:
      host: localhost
      port: 3306
      name: inventorypagesrecoded
      table: inventorydata
      user: root
      password: ''

inventory-settings:
  # Để là 0 nếu không muốn cho người chơi bất kì trang nào
  # Không thể để số thấp hơn 0. Nếu để số thấp hơn 0, sẽ tự động coi là 0
  max-page-default: 0
  # Nếu tùy chọn này được bật, thì khi người chơi vào máy chủ sẽ hiển thị trang đang mở trước đó
  # ví dụ lúc thoát game đang ở trang 5 thì khi vào game sẽ hiển thị trang 5
  # Nếu tắt tùy chọn này, thì trang hiển thị khi người chơi vào máy chủ sẽ luôn luôn là trang đầu
  use-saved-current-page: true