name: InventoryPagesRecoded
version: '${project.version}'
main: me.kevinnovak.inventorypages.InventoryPages
api-version: '1.13'
authors:
  - KevinNovak
  - Cortez_Romeo
description: Add pages to inventories for expansive storage!
commands:
  inventorypagesrecoded:
    description: Main command
    aliases:
      - inventorypages
      - inventoryp
      - tuidopage
      - tudopage
      - tuidopages
  clear:
    description: Clear inventory
    aliases:
      - clearinventory
      - ci